[package]
name = "randomprime"
version = "0.2.3"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[dependencies]
adler32 = "1.0"
clap = "2.9"
encoding = "0.2"
flate2 = "1.0"
memmap = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7"
rand = "0.4"
winapi = "0.3"

dol_symbol_table = { path = "dol_symbol_table" }
nod_wrapper = { path = "nod_wrapper" }
ppcasm = { path = "ppcasm" }
reader_writer = { path = "reader_writer" }
resource_info_table = { path = "resource_info_table" }
structs = { path = "structs" }

[build-dependencies]
walkdir = "2"

dol_linker = { path = "dol_linker" }

[profile.release]
lto = true
panic = "unwind"

[workspace]
members = [
    "auto_struct_macros",
    "dol_linker",
    "dol_symbol_table",
    "macro_file_proxy",
        "macro_file_proxy/macro_file_proxy_proc_macro",
    "nod_wrapper",
    "ppcasm",
        "ppcasm/ppcasm_macro",
    "reader_writer",
    "resource_info_table",
    "structs",
]

[lib]
name = "randomprime"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]
