[package]
name = "dol_linker"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
enum-map = "0.6"
goblin = "0.1"
memmap = "0.7"
scroll = { version = "0.10", features = ["derive"] }
snafu = "0.6"

