[package]
name = "generated"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[dependencies]
macro_file_proxy = { path = "macro_file_proxy" }
reader_writer = { path = "../reader_writer" }

[build-dependencies]
walkdir = "2"
dol_linker = { path = "../dol_linker" }
